Add clean_observers management commands
genialis/resolwe pull request #1040
Opened 2023-08-30 08:44 UTC by gregorjerse

that cleans old subscriptions

2023-08-30 09:01 UTC, plojyon requested changes

2023-08-30 09:01 UTC, plojyon commented on resolwe/observers/management/commands/clean_observers.py
> +DELETE_OLDER_THAN = 1
Specify threshold in hours to allow more granular control.

2023-09-01 08:30 UTC, plojyon commented on resolwe/observers/management/commands/clean_observers.py
> +        Observer.objects.filter(subscriptions__isnull=True).delete()
Add some logging so we know the cronjob ran?

2023-09-10 09:17 UTC, plojyon approved these changes
looks good

2023-09-11 06:52 UTC, gregorjerse commented
Duplicate #1039

2023-09-11 06:52 UTC, closed without merging

2023-09-12 10:35 UTC, dblenkus commented on resolwe/observers/management/commands/clean_observers.py
> +        deleted_subscriptions = Subscription.objects.filter(
It is more pythonic to write `deleted_subscriptions, _` instead of using `[0]`