Add OpenAPI schema
genialis/resolwe pull request #1054
Opened 2023-09-28 08:46 UTC by plojyon

2023-09-29 07:03 UTC, gregorjerse requested changes

2023-09-29 07:03 UTC, gregorjerse commented on resolwe/flow/views/mixins.py
> +        parameters=[OpenApiParameter("name", str)], responses={status.HTTP_200_OK: bool}
How about 400 and 401?

2023-09-29 07:18 UTC, plojyon commented on resolwe/flow/views/mixins.py
> +    @extend_schema(responses={200: bool, 401: None})
I try not to document 4xx and 5xx errors for simplicity. This was amended in a later commit, but wasn't squashed.

2023-09-29 07:21 UTC, plojyon commented on resolwe/permissions/mixins.py
> +    users = serializers.DictField(
Dict keys cannot be integers, unfortunately.

2023-09-29 10:19 UTC, gregorjerse requested changes

2023-09-29 10:19 UTC, gregorjerse commented on resolwe/flow/filters.py
> +        def collection_permission_filter(self, qs, value: str):
Add type to the queryset (argument qs).

2023-09-29 10:19 UTC, gregorjerse commented on resolwe/flow/filters.py
> +        def filter_permissions(self, qs, value: str, original_filter):
Add type hint to the queryset. You could also type `original_filter`: it is a callable that accepts a queryset and a value and returns a new queryset.

2023-09-29 10:19 UTC, gregorjerse commented on resolwe/permissions/mixins.py
> +    users = serializers.DictField(
Can we at least add a comment they represent username/group ?

2023-10-02 06:52 UTC, gregorjerse approved these changes

2023-10-02 06:53 UTC, merged